version: '3.6'
services:
    vncserver:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: ${DOCKER_RESTART:-no}
        ports:
            - 4444:4444
            - ${DOCKER_VNC_PORT:-7900}:5900
        volumes:
            - /dev/shm:/dev/shm
        environment:
            - VNC_PASSWORD=${VNC_PASSWORD:-password}
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.10.64/27
